"""The native-text PDF API path, exercised with a PDF generated by the sample script."""

from pathlib import Path

from fastapi.testclient import TestClient

from samples.make_sample_pdfs import write_pdf

COMPLAINT = (
    "Subject: Cracked capsules - Amoxinova 500 mg Capsules, batch AMX-24118\n"
    "Meridian Pharmacy Group found 12 cracked capsules on 2026-06-14.\n"
    "Contact: quality@meridianpharmacy.example"
)

def test_uploaded_pdf_is_analysed(client: TestClient, mock_llm: None, tmp_path: Path) -> None:
    pdf = tmp_path / "complaint.pdf"
    write_pdf(COMPLAINT, pdf)

    with pdf.open("rb") as handle:
        response = client.post(
            "/api/complaints/analyze",
            files={"file": ("complaint.pdf", handle, "application/pdf")},
        )

    assert response.status_code == 200
    body = response.json()
    assert body["input_filename"] == "complaint.pdf"
    assert body["extracted_fields"]["batch_lot_number"] == "AMX-24118"


def test_upload_larger_than_the_limit_is_rejected(client: TestClient) -> None:
    oversized = b"%PDF-1.4\n" + b"0" * (6 * 1024 * 1024)

    response = client.post(
        "/api/complaints/analyze", files={"file": ("big.pdf", oversized, "application/pdf")}
    )

    assert response.status_code == 413
    assert response.json()["error"]["code"] == "payload_too_large"
