"""create complaints table

Revision ID: f66f403cf40a
Revises:
Create Date: 2026-07-26 21:45:21.380148
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f66f403cf40a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_number', sa.String(length=20), nullable=False),
    sa.Column('complaint_source', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_contact', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_strength_grade', sa.String(length=128), nullable=True),
    sa.Column('batch_lot_number', sa.String(length=128), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('quantity_affected', sa.Float(), nullable=True),
    sa.Column('quantity_unit', sa.String(length=64), nullable=True),
    sa.Column('complaint_type', sa.String(length=64), nullable=True),
    sa.Column('complaint_date', sa.Date(), nullable=True),
    sa.Column('complaint_details', sa.Text(), nullable=True),
    sa.Column('initial_severity', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('risk_rationale', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('completeness_score', sa.Integer(), nullable=True),
    # JSONB on PostgreSQL, plain JSON on SQLite.
    sa.Column('missing_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('root_cause_recommendations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('capa_recommendations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('input_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_batch_lot_number'), ['batch_lot_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_complaint_number'), ['complaint_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_complaints_complaint_type'), ['complaint_type'], unique=False)
        batch_op.create_index('ix_complaints_product_batch', ['product_name', 'batch_lot_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_product_name'), ['product_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_product_name'))
        batch_op.drop_index('ix_complaints_product_batch')
        batch_op.drop_index(batch_op.f('ix_complaints_complaint_type'))
        batch_op.drop_index(batch_op.f('ix_complaints_complaint_number'))
        batch_op.drop_index(batch_op.f('ix_complaints_batch_lot_number'))

    op.drop_table('complaints')
    # ### end Alembic commands ###
